DROP TABLE GEEKCONSULTATION IF EXISTS;
DROP TABLE GEEKINTEREST IF EXISTS;
DROP TABLE GEEK IF EXISTS;
DROP TABLE INTEREST IF EXISTS;

CREATE TABLE GEEK (id int, lastName varchar(30),firstName varchar(30),age int,sexe boolean,mail varchar(30));

CREATE TABLE INTEREST (id int, name varchar(30));

CREATE TABLE GEEKINTEREST(GEEKID int,INTERESTID int);

CREATE TABLE GEEKCONSULTATION (id int,date timestamp,fromIP varchar(11),geekid int);

ALTER TABLE GEEK ADD CONSTRAINT PK_GEEK PRIMARY KEY(id);
ALTER TABLE INTEREST ADD CONSTRAINT PK_INTEREST PRIMARY KEY(id);
ALTER TABLE GEEKINTEREST ADD CONSTRAINT PK_GEEKINTEREST PRIMARY KEY(GEEKID,INTERESTID);
ALTER TABLE GEEKCONSULTATION ADD CONSTRAINT PK_GEEKCONSULTATION PRIMARY KEY(id);

ALTER TABLE GEEKCONSULTATION ADD CONSTRAINT FK_GEEKCONSULTATION_GEEKID_GEEK FOREIGN KEY(GEEKID) REFERENCES GEEK(id);
ALTER TABLE GEEKINTEREST ADD CONSTRAINT FK_GEEKINTEREST_GEEKID_GEEK FOREIGN KEY(GEEKID) REFERENCES GEEK(id);
ALTER TABLE GEEKINTEREST ADD CONSTRAINT FK_GEEKINTEREST_INTERESTID_INTEREST FOREIGN KEY(INTERESTID) REFERENCES INTEREST(ID);
